name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm clean-install
      - run: npm test
      - uses: codecov/codecov-action@v2
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12.20'
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm clean-install
      - run: npm test
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: >-
            POST
            /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: form8ion
          repo: javascript
          ref: ${{ github.ref }}
          workflow_id: release.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
